### ISSUE TITLE
When trying to import module 'ngx-sticky' can't be found

### ISSUE THREAD

**Issue by bjonesy** [barbared/ngx-sticky#1]
After npm install, when trying to register in the Sticky module in my @NgModule I get an error saying it can't find the `ngx-sticky` npm module.  `ERROR in src/app/program/program.module.ts(6,36): error TS2307: Cannot find module 'ngx-sticky'.` I was adding this on a brand new angular cli instance to test it out.  Just a normal angular cli generated app trying to import this module.  

Thanks

**Comment by barbared** [comment]
Hi bjonesy,
Thank you for your feedback.
We had an issue with the first version of the component. In the version 2.0.0 we have addressed the problem and we have changed the way in which the module should be imported in your app.

Regards.
